apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: istio-ingress-jwt
  namespace: gke-system
spec:
  targets:
  - name: istio-ingress
    ports:
    - name: http2
    - name: https
  origins:
  - jwt:
      issuer: https://accounts.google.com
      jwksUri: https://www.googleapis.com/oauth2/v3/certs
  originIsOptional: true # use authorization policy to allow or deny request
  principalBinding: USE_ORIGIN